frame_rate = 60
tick_rate = 50

[ui]
use_nerd_font_icons = false
ui_scale = 100
show_help_bar = false
show_preview_panel = true
input_bar_position = "top"
theme = "tokyonight"

[previewers.file]
theme = "tokyonight_nigh"

[keybindings.Channel]
quit = "esc"
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
select_next_page = "pagedown"
select_prev_page = "pageup"
scroll_preview_half_page_down = "ctrl-d"
scroll_preview_half_page_up = "ctrl-u"
toggle_selection_down = "tab"
toggle_selection_up = "backtab"
confirm_selection = "enter"
copy_entry_to_clipboard = "ctrl-y"
toggle_remote_control = "ctrl-r"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[keybindings.RemoteControl]
quit = "esc"
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_remote_control = "ctrl-r"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[keybindings.SendToChannel]
quit = "esc"
select_next_entry = ["down", "ctrl-n", "ctrl-j"]
select_prev_entry = ["up", "ctrl-p", "ctrl-k"]
select_next_page = "pagedown"
select_prev_page = "pageup"
select_entry = "enter"
toggle_send_to_channel = "ctrl-s"
toggle_help = "ctrl-g"
toggle_preview = "ctrl-o"

[shell_integration.commands]
"export" = "env"
"unset" = "env"
"cd" = "dirs"
"ls" = "dirs"
"rmdir" = "dirs"
"cat" = "files"
"less" = "files"
"head" = "files"
"tail" = "files"
"vim" = "files"
"bat" = "files"
"git add" = "git-diff"
"git checkout" = "git-branch"
"git branch -d" = "git-branch"
"docker run" = "docker-images"
"nvim" = "git-repos"